### PR TITLE
Fixed the scroll issue on the edit page

### PR DESCRIPTION
**Pull request by Duncan-Ireri**

### CODE REVIEW

**Comment by StanleyMasinde** [comment]
@Duncan-Ireri I’ll review this ASAP

**Comment by StanleyMasinde** [comment]
@Duncan-Ireri did you create this branch from main? It looks like it has unreleased features from #35. Which are very unstable.

**Comment by Duncan-Ireri** [comment]
Yeah, was of the idea that was your release branch as I did not see a `dev` or `development` branch. You could rebase both and get to work on the bugs. PS: I did not include the search feature in my PR.

**Comment by StanleyMasinde** [comment]
@Duncan-Ireri just so we are clear, did your create your fix branch from main?

**Comment by StanleyMasinde** [comment]
I’ve accidentally deleted hiyo branch 😂 @Duncan-Ireri I guess we are stuck with this PR for that feature.

**Comment by StanleyMasinde** [comment]
I’ve restored it.

**Comment by Duncan-Ireri** [comment]
> @Duncan-Ireri just so we are clear, did your create your fix branch from main?

Yes, it is

**Pull request merged**
